### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by CargoCultScientist** [cfreeman/tsa#1]
- We need to include in the metadata:

    1. the date published (you already have that in the name of the file)
    2. the names of everyone involved, if you look at how it's done in reference software like Endnote or Mendeley, then it's usually done like "Sachs T., Savage Adam, Giertz, S." (for example), and the software automatically knows what's up as long as you keep to the format of "Lastname Firstname, Lastname F." - this gets also important later when I publish the zines. Because some of the canonical material has also several authors, for example, the Haiku book or the giant work by Celant 
   3. the type of source, as a tag format. (for now, I propose: lecture, interview, zine, book; but we could also extend this to include like: podcast, conversation, radio, TV, SoundCloud, youtube, Vimeo)
  4. an "at risk" variable: a flag that indicates whether this file is at risk of being taken down because of copyright violations. Whenever we do not have a source link to the original, this should be true.
   
  
- It's important to note that the library is canon only. Nothing that doesn't contain at least some interview elements can be allowed. 
- We also can't make the metadata too complicated otherwise it's a bitch to fill out. 

Edit: One 'thing' per issue have split some other issues into their own seperate item.

**Comment by cfreeman** [comment]
i. The frontmatter metadata block also contains 'date', which was when the item was published.

ii. Added a 'people' metadata tag (there is no special display for this yet).

iii. At the moment the 'type' tag has the following entries:
- lecture (A presentation given to an audience)
- interview (A conversation / dialogue between Tom Sachs and others)
- walkaround (A tour of content presented within a museum)

Other types that have not been used yet:
- zine (we need a clear distinction between a zine and a book).
- book
- tutorial (office hours / love letter to plywood / other studio instruction)

type tags should not be conflated with the source of content, so type tags would **not** include things like SoundCloud, YouTube or Vimeo. We have a seperate tags for links to the source of content.

iv. I'm hesitant to add 'at risk', everything in the collection is at risk until we sort out a solution for #3, we can discuss further in that issue.
